// Mock data for ksa1 - Twitter-like Saudi platform

export const LOGO_URL = 'https://customer-assets.emergentagent.com/job_social-feed-269/artifacts/4uw736wq_IMG_5636.jpeg';

export const currentUser = {
  id: 'u_me',
  name: 'أنت',
  username: 'you',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200&h=200&fit=crop',
  cover: 'https://images.unsplash.com/photo-1578895101408-1a36b834405b?w=1200&h=400&fit=crop',
  bio: 'مستخدم جديد في ksa1 🇸🇦',
  location: 'الرياض',
  joined: 'يوليو 2025',
  following: 142,
  followers: 87,
  verified: false,
};

export const users = [
  {
    id: 'u1',
    name: 'محمد العتيبي',
    username: 'mohammed_otb',
    avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=200&h=200&fit=crop',
    bio: 'مهندس برمجيات | شغوف بالتقنية والذكاء الاصطناعي',
    verified: true,
  },
  {
    id: 'u2',
    name: 'سارة القحطاني',
    username: 'sara_q',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    bio: 'مصممة جرافيك | عاشقة للقهوة ☕',
    verified: false,
  },
  {
    id: 'u3',
    name: 'عبدالله الشمري',
    username: 'abdullah_sh',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop',
    bio: 'صحفي رياضي | الهلال 💙',
    verified: true,
  },
  {
    id: 'u4',
    name: 'نورة الزهراني',
    username: 'noura_z',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    bio: 'كاتبة محتوى | أحب القراءة والسفر ✈️',
    verified: false,
  },
  {
    id: 'u5',
    name: 'فيصل الدوسري',
    username: 'faisal_d',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop',
    bio: 'مستثمر | ريادة أعمال',
    verified: true,
  },
  {
    id: 'u6',
    name: 'ريما السبيعي',
    username: 'reema_s',
    avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop',
    bio: 'طبيبة أسنان | أم لطفلين',
    verified: false,
  },
];

export const tweets = [
  {
    id: 't1',
    userId: 'u1',
    content: 'صباح الخير من الرياض ☀️ يوم جديد مليان فرص. اللي يبدأ يومه بنية حلوة، ينهيه بإنجاز 💪',
    image: null,
    timestamp: 'منذ 5 دقائق',
    likes: 234,
    retweets: 45,
    replies: 12,
    views: 3200,
    liked: false,
    retweeted: false,
  },
  {
    id: 't2',
    userId: 'u3',
    content: 'مباراة الليلة حماسية! 🔥⚽ الهلال يستحق الفوز بعد الأداء الجبار. مين توقعاتكم للنتيجة؟',
    image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=500&fit=crop',
    timestamp: 'منذ 15 دقيقة',
    likes: 892,
    retweets: 156,
    replies: 89,
    views: 12400,
    liked: true,
    retweeted: false,
  },
  {
    id: 't3',
    userId: 'u2',
    content: 'خلصت تصميم جديد اليوم وأنا فخورة فيه ✨ التصميم مو بس ألوان وأشكال، هو حكاية تنقل إحساس.',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b8?w=800&h=600&fit=crop',
    timestamp: 'منذ 32 دقيقة',
    likes: 412,
    retweets: 67,
    replies: 34,
    views: 5600,
    liked: false,
    retweeted: true,
  },
  {
    id: 't4',
    userId: 'u5',
    content: 'نصيحة للمبتدئين في ريادة الأعمال: ابدأ صغير، فكر كبير، وتعلم من كل خطوة. الفشل مو نهاية، هو بداية تعلم.',
    image: null,
    timestamp: 'منذ ساعة',
    likes: 1240,
    retweets: 320,
    replies: 78,
    views: 18900,
    liked: false,
    retweeted: false,
  },
  {
    id: 't5',
    userId: 'u4',
    content: 'انتهيت من قراءة رواية رائعة الليلة 📚 الكتب أبواب لعوالم لا حدود لها. شاركوني آخر كتاب قرأتوه؟',
    image: 'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=500&fit=crop',
    timestamp: 'منذ ساعتين',
    likes: 567,
    retweets: 89,
    replies: 145,
    views: 7800,
    liked: true,
    retweeted: false,
  },
  {
    id: 't6',
    userId: 'u6',
    content: 'تذكير: شربك للماء بانتظام يحسن صحة فمك وأسنانك 💧🦷 خلوا الماء أول خيار لكم.',
    image: null,
    timestamp: 'منذ 3 ساعات',
    likes: 198,
    retweets: 42,
    replies: 18,
    views: 2900,
    liked: false,
    retweeted: false,
  },
  {
    id: 't7',
    userId: 'u1',
    content: 'الذكاء الاصطناعي يغير العالم كل يوم، والسعودية في مقدمة الدول اللي تستثمر فيه 🇸🇦 رؤية 2030 تتحقق.',
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&h=500&fit=crop',
    timestamp: 'منذ 5 ساعات',
    likes: 2103,
    retweets: 567,
    replies: 234,
    views: 34000,
    liked: false,
    retweeted: false,
  },
];

export const trends = [
  { category: 'الترند في السعودية', tag: '#رؤية_2030', posts: '125 ألف تغريدة' },
  { category: 'رياضة · ترند', tag: '#الهلال_النصر', posts: '89.2 ألف تغريدة' },
  { category: 'تقنية · ترند', tag: '#الذكاء_الاصطناعي', posts: '45.6 ألف تغريدة' },
  { category: 'الترند في السعودية', tag: '#الرياض', posts: '32 ألف تغريدة' },
  { category: 'ترفيه · ترند', tag: '#موسم_الرياض', posts: '28.4 ألف تغريدة' },
];

export const notifications = [
  { id: 'n1', type: 'like', userId: 'u2', text: 'أعجب بتغريدتك', tweetId: 't1', time: 'منذ 10 دقائق' },
  { id: 'n2', type: 'follow', userId: 'u5', text: 'بدأ بمتابعتك', time: 'منذ 30 دقيقة' },
  { id: 'n3', type: 'retweet', userId: 'u3', text: 'أعاد نشر تغريدتك', tweetId: 't2', time: 'منذ ساعة' },
  { id: 'n4', type: 'reply', userId: 'u4', text: 'رد على تغريدتك: "كلام رائع! شكراً لك"', tweetId: 't1', time: 'منذ 3 ساعات' },
  { id: 'n5', type: 'like', userId: 'u6', text: 'أعجب بتغريدتك', tweetId: 't5', time: 'أمس' },
];

export const messages = [
  {
    id: 'm1',
    userId: 'u1',
    lastMessage: 'تمام، نتقابل بكرا الساعة 5',
    time: 'منذ 5 دقائق',
    unread: true,
  },
  {
    id: 'm2',
    userId: 'u2',
    lastMessage: 'شكراً جزيلاً على المساعدة!',
    time: 'منذ ساعة',
    unread: false,
  },
  {
    id: 'm3',
    userId: 'u4',
    lastMessage: 'الكتاب اللي رشحته رائع 📚',
    time: 'أمس',
    unread: false,
  },
];
